name: restaurant_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^1.2.1
  google_fonts: ^6.2.1
  lottie: ^2.6.0
  sqflite: ^2.2.8+5
  path: ^1.8.4
  shared_preferences: ^2.1.1
  workmanager: ^0.6.0-dev.7
  flutter_local_notifications: ^17.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.2
  integration_test:
    sdk: flutter
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/loading.json
    - assets/lottie/error.json
